version: '3.8'

services:
  server-container:
    image: rizadwiandhika/hospital-management-system-api:latest
    build:
      context: .
      dockerfile: Dockerfile.aws
    depends_on:
      - mysql-container
    container_name: server-container
    hostname: server-container
    networks:
      - hospital-network
    volumes:
      - server-volume:/app/files
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    hostname: mysql-container
    networks:
      - hospital-network
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?database password not set}
      - TZ=${TIMEZONE:?database timezone not set}
    ports:
      - 3306:3306
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+07:00'
      ]

volumes:
  mysql-volume:
  server-volume:

networks:
  hospital-network:
    driver: bridge
