// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	nurses "github.com/final-project-alterra/hospital-management-system-api/features/nurses"
	mock "github.com/stretchr/testify/mock"
)

// IBusiness is an autogenerated mock type for the IBusiness type
type IBusiness struct {
	mock.Mock
}

// CreateNurse provides a mock function with given fields: nurse
func (_m *IBusiness) CreateNurse(nurse nurses.NurseCore) error {
	ret := _m.Called(nurse)

	var r0 error
	if rf, ok := ret.Get(0).(func(nurses.NurseCore) error); ok {
		r0 = rf(nurse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditNurse provides a mock function with given fields: nurse
func (_m *IBusiness) EditNurse(nurse nurses.NurseCore) error {
	ret := _m.Called(nurse)

	var r0 error
	if rf, ok := ret.Get(0).(func(nurses.NurseCore) error); ok {
		r0 = rf(nurse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditNursePassword provides a mock function with given fields: id, updatedBy, oldPassword, newPassword
func (_m *IBusiness) EditNursePassword(id int, updatedBy int, oldPassword string, newPassword string) error {
	ret := _m.Called(id, updatedBy, oldPassword, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) error); ok {
		r0 = rf(id, updatedBy, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindNurseByEmail provides a mock function with given fields: email
func (_m *IBusiness) FindNurseByEmail(email string) (nurses.NurseCore, error) {
	ret := _m.Called(email)

	var r0 nurses.NurseCore
	if rf, ok := ret.Get(0).(func(string) nurses.NurseCore); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(nurses.NurseCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNurseById provides a mock function with given fields: id
func (_m *IBusiness) FindNurseById(id int) (nurses.NurseCore, error) {
	ret := _m.Called(id)

	var r0 nurses.NurseCore
	if rf, ok := ret.Get(0).(func(int) nurses.NurseCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(nurses.NurseCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNurses provides a mock function with given fields:
func (_m *IBusiness) FindNurses() ([]nurses.NurseCore, error) {
	ret := _m.Called()

	var r0 []nurses.NurseCore
	if rf, ok := ret.Get(0).(func() []nurses.NurseCore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]nurses.NurseCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNursesByIds provides a mock function with given fields: ids
func (_m *IBusiness) FindNursesByIds(ids []int) ([]nurses.NurseCore, error) {
	ret := _m.Called(ids)

	var r0 []nurses.NurseCore
	if rf, ok := ret.Get(0).(func([]int) []nurses.NurseCore); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]nurses.NurseCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveNurseById provides a mock function with given fields: id, updatedBy
func (_m *IBusiness) RemoveNurseById(id int, updatedBy int) error {
	ret := _m.Called(id, updatedBy)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(id, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
