// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	patients "github.com/final-project-alterra/hospital-management-system-api/features/patients"
	mock "github.com/stretchr/testify/mock"
)

// IData is an autogenerated mock type for the IData type
type IData struct {
	mock.Mock
}

// DeletePatientById provides a mock function with given fields: id, updatedBy
func (_m *IData) DeletePatientById(id int, updatedBy int) error {
	ret := _m.Called(id, updatedBy)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(id, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPatient provides a mock function with given fields: patient
func (_m *IData) InsertPatient(patient patients.PatientCore) error {
	ret := _m.Called(patient)

	var r0 error
	if rf, ok := ret.Get(0).(func(patients.PatientCore) error); ok {
		r0 = rf(patient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectPatientById provides a mock function with given fields: id
func (_m *IData) SelectPatientById(id int) (patients.PatientCore, error) {
	ret := _m.Called(id)

	var r0 patients.PatientCore
	if rf, ok := ret.Get(0).(func(int) patients.PatientCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(patients.PatientCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectPatientByNIK provides a mock function with given fields: nik
func (_m *IData) SelectPatientByNIK(nik string) (patients.PatientCore, error) {
	ret := _m.Called(nik)

	var r0 patients.PatientCore
	if rf, ok := ret.Get(0).(func(string) patients.PatientCore); ok {
		r0 = rf(nik)
	} else {
		r0 = ret.Get(0).(patients.PatientCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectPatients provides a mock function with given fields:
func (_m *IData) SelectPatients() ([]patients.PatientCore, error) {
	ret := _m.Called()

	var r0 []patients.PatientCore
	if rf, ok := ret.Get(0).(func() []patients.PatientCore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]patients.PatientCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectPatientsByIds provides a mock function with given fields: ids
func (_m *IData) SelectPatientsByIds(ids []int) ([]patients.PatientCore, error) {
	ret := _m.Called(ids)

	var r0 []patients.PatientCore
	if rf, ok := ret.Get(0).(func([]int) []patients.PatientCore); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]patients.PatientCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePatient provides a mock function with given fields: patient
func (_m *IData) UpdatePatient(patient patients.PatientCore) error {
	ret := _m.Called(patient)

	var r0 error
	if rf, ok := ret.Get(0).(func(patients.PatientCore) error); ok {
		r0 = rf(patient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
